### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by redtux** [r0oth3x49/wp-plugin-checker#1]
Hi, thank you for this app! Have you tested it recently? It seems to me that it's not working.

### How to reproduce
```bash
git clone https://github.com/r0oth3x49/wp-plugin-checker.git
cd wp-plugin-checker
pip install -r requirements.txt

python wp-check.py -u https://jquery.com/ -d
  File "wp-check.py", line 185
    print '\n' + sb + fg + '[+]' + sb + fy + ' TOR: configuring tor proxy...'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('\n' + sb + fg + '[+]' + sb + fy + ' TOR: configuring tor proxy..
.')?
```
### My system
```bash
$ lsb_release -d
Description:    Ubuntu 20.04.2 LTS

$ python --version
Python 3.8.5

$ pip --version
pip 21.0 from /home/redtux/.local/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by r0oth3x49** [comment]
@redtux it was developed on python2 i will take some time out to port it to python3 or if you can then send me a PR.

**Comment by redtux** [comment]
Alright, thx! Then I'll try with Python 2 first. In case I figure out what needs to be changed to work with Python 3, I'll submit a PR. 🎉

**Comment by r0oth3x49** [comment]
> 
> 
> Alright, thx! Then I'll try with Python 2 first. In case I figure out what needs to be changed to work with Python 3, I'll submit a PR. tada

try changing with 2to3 i think it should work as i didn't used any fancy libs in this but the default one from python.

**Comment by redtux** [comment]
Hi @r0oth3x49, good news! Your idea of transforming the code via 2to3 seems to work fine. :tada: 

```bash
python wp-check.py -u https://jquery.com/ -b
[+] URL: https://jquery.com/
[+] Started: Sun Jan 31 08:28:57 2021
[+] Wordlist: using default wordlist 'plugins.txt'

-------------------------------------------------------------------------
[=======                                 ] ( 164/1000 ) 16.40%
```

I will now fork this repo, push my changes, and make a pull request as suggested.

Thanks for your help and for all the nice apps! :heart_eyes_cat:

**Comment by redtux** [comment]
Thanks for merging! 🚀 I kept testing with further sites, and everything works fine. ✨
